"""empty message

Revision ID: 70761afa54ae
Revises: 34ab147c28aa
Create Date: 2022-04-28 23:25:04.160585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70761afa54ae'
down_revision = '34ab147c28aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residues', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'residues', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'residues', type_='foreignkey')
    op.drop_column('residues', 'user_id')
    # ### end Alembic commands ###
