"""empty message

Revision ID: b809a8f786bf
Revises: 2aad708aedd1
Create Date: 2022-04-28 20:52:51.469727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b809a8f786bf'
down_revision = '2aad708aedd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residues',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('collected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('residues')
    # ### end Alembic commands ###
